# Generated by Django 4.2.5 on 2023-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contacts',
            field=models.CharField(max_length=30, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_full',
            field=models.BooleanField(verbose_name='Полная'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
    ]
