# Generated by Django 4.2.5 on 2023-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=None, max_length=20, verbose_name='URL'),
        ),
    ]
