# Generated by Django 4.2.5 on 2023-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(default=None, max_length=20, unique=True, verbose_name='URL'),
        ),
    ]
